apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap_apache.name }}
  namespace: {{ .Values.namespace }}

data:
  
{{- range $path, $_ := (.Files.Glob "apacheconf/*") }}
  {{ trimPrefix "apacheconf/" $path }}: |+
    {{- tpl ($.Files.Get $path) $ | nindent 4 }}
{{ end -}}