apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "apache.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "apache.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "apache.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "apache.selectorLabels" . | nindent 8 }}
    spec:
    #   initContainers:
    #     - name: {{ .Values.initcontainer.name}}
    #       image: {{ .Values.initcontainer.image }}
    #       imagePullPolicy: {{ .Values.image.pullPolicy }}
    #       command: ['ls -la']
          # command: ['chown', 'apache:apache','/storage','/data','/var/www/html' , '/var/log/httpd']
          # command: ['chown', 'apache:apache', '/storage/pack']
          # command: ['chown', 'apache:apache', '/storage/other']
          # command: ['chown', 'apache:apache', '/storage/other/logs']
          # command: ['chown', 'apache:apache', '/storage/other/pack']
          # command: ['chown', 'apache:apache','/storage','/data','/var/www/html' , '/var/log/apache2']
          # command: ['chown', 'apache:apache', '/storage/pack']
          # command: ['chown', 'apache:apache', '/storage/other']
          # command: ['chown', 'apache:apache', '/storage/other/logs']
          # command: ['chown', 'apache:apache', '/storage/other/pack']
          # command: ['chown', 'apache:apache', '/storage/microgridlakeasiaone']
          # command: ['chown', 'apache:apache', '/storage/microgridlakeasiaone/logs']
          # command: ['chown', 'apache:apache', '/data/mglasiaone/']
          # command: ['chown', 'apache:apache', '/data/mglasiaone/csv-to-microgridlakeasiaone/']
          # command: ['chown', 'apache:apache', '/storage/microgridlakeasiatwo']
          # command: ['chown', 'apache:apache', '/storage/microgridlakeasiatwo/logs']
          # command: ['chown', 'apache:apache', '/data/mglasiatwo/']
          # command: ['chown', 'apache:apache', '/data/mglasiatwo/csv-to-microgridlakeasiatwo/']
          # command: ['chown', 'apache:apache', '/storage/microgridlakeasiathree']
          # command: ['chown', 'apache:apache', '/storage/microgridlakeasiathree/logs']
          # command: ['chown', 'apache:apache', '/data/mglasiathree/']
          # command: ['chown', 'apache:apache', '/data/mglasiathree/csv-to-microgridlakeasiathree/']
          # command: ['chown', 'apache:apache', '/storage/microgridlakeasiafour']
          # command: ['chown', 'apache:apache', '/storage/microgridlakeasiafour/logs']
          # command: ['chown', 'apache:apache', '/data/mglasiafour/']
          # command: ['chown', 'apache:apache', '/data/mglasiafour/csv-to-microgridlakeasiafour/']
          # command: ['chown', 'apache:apache', '/storage/microgridlakeasiafive']
          # command: ['chown', 'apache:apache', '/storage/microgridlakeasiafive/logs']
          # command: ['chown', 'apache:apache', '/data/mglasiafive/']
          # command: ['chown', 'apache:apache', '/data/mglasiafive/csv-to-microgridlakeasiafive/']
          # command: ['chown', 'apache:apache', '/storage/microgridlakeasiasix']
          # command: ['chown', 'apache:apache', '/storage/microgridlakeasiasix/logs']
          # command: ['chown', 'apache:apache', '/data/mglasiasix/']
          # command: ['chown', 'apache:apache', '/data/mglasiasix/csv-to-microgridlakeasiasix/']
          # command: ['chown', 'apache:apache', '/storage/smallutilitylakeasia']
          # command: ['chown', 'apache:apache', '/storage/smallutilitylakeasia/logs']
          # command: ['chown', 'apache:apache', '/data/sulasia/']
          # command: ['chown', 'apache:apache', '/data/sulasia/csv-to-smallutilitylakeasia/']
          # command: ['chown', 'apache:apache', '/storage/iplonlakeasia']
          # command: ['chown', 'apache:apache', '/storage/iplonlakeasia/logs']
          # command: ['chown', 'apache:apache', '/data/iplasia/']
          # command: ['chown', 'apache:apache', '/data/iplasia/csv-to-iplonlakeasia/']
          # command: ['chown', 'apache:apache', '/storage/ampluslakeasia']
          # command: ['chown', 'apache:apache', '/storage/ampluslakeasia/logs']
          # command: ['chown', 'apache:apache', '/data/amplasia/']
          # command: ['chown', 'apache:apache', '/data/amplasia/csv-to-ampluslakeasia/']
          # command: ['chown', 'apache:apache', '/storage/largeutilitylakeasia']
          # command: ['chown', 'apache:apache', '/storage/largeutilitylakeasia/logs']
          # command: ['chown', 'apache:apache', '/data/lulasia/']
          # command: ['chown', 'apache:apache', '/data/lulasia/csv-to-largeutilitylakeasia/']
          # command: ['chown', 'apache:apache', '/storage/microgridlakeafrica']
          # command: ['chown', 'apache:apache', '/storage/microgridlakeafrica/logs']
          # command: ['chown', 'apache:apache', '/data/mglafrica/']
          # command: ['chown', 'apache:apache', '/data/mglafrica/csv-to-microgridlakeafrica/']
          # command: ['chown', 'apache:apache', '/storage/microgridlakeamerica']
          # command: ['chown', 'apache:apache', '/storage/microgridlakeamerica/logs']
          # command: ['chown', 'apache:apache', '/data/mglamerica/']
          # command: ['chown', 'apache:apache', '/data/mglamerica/csv-to-microgridlakeamerica/']
          # command: ['chmod', '777','/storage','/var/log/apache2']
          # command: ['chmod', '777','/data/','/var/log/apache2']
          # command: ['chmod', '777','/storage/pack']
          # command: ['chmod', '777','/storage/other']
          # command: ['chmod', '777','/storage/other/logs']
          # command: ['chmod', '777','/storage/other/pack']
          # command: ['chmod', '777','/storage/microgridlakeasiaone']
          # command: ['chmod', '777','/storage/microgridlakeasiaone/logs']
          
          # securityContext:
          #   runAsUser: {{ .Values.securityContext.runAsUser }}
          #   privileged: {{ .Values.securityContext.privileged }}
          # volumeMounts:
          #   - name: {{ .Values.igate_mount.name }}
          #     mountPath:  {{ .Values.igate_mount.mountPath }}
          #   - name:  {{ .Values.igate_apache_logs.name }}
          #     mountPath: {{ .Values.igate_apache_logs.mountPath}}
          #   - mountPath: {{ .Values.csv_to_iporting.mountPath }}
          #     name: {{ .Values.csv_to_iporting.name }}  
              
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
          - name: {{ .Values.service.portName }}
            containerPort: 80
            protocol: TCP

          volumeMounts:
            - mountPath: {{ .Values.igate_mount.mountPath }}
              name: {{ .Values.igate_mount.name }}
            
            - mountPath: {{ .Values.csv_to_iporting.mountPath }}
              name: {{ .Values.csv_to_iporting.name }}
            
            - mountPath: {{ .Values.igate_apache_logs.mountPath }}
              name:  {{ .Values.igate_apache_logs.name }}

            - mountPath: {{ .Values.configmap_getdataphp.mountpath }}
              name:  {{ .Values.configmap_getdataphp.name }}
              subPath: {{ .Values.configmap_getdataphp.subpath }}

            - mountPath: {{ .Values.configmap_getdatavariablephp.mountpath }}
              name:  {{ .Values.configmap_getdatavariablephp.name }}
              subPath: {{ .Values.configmap_getdatavariablephp.subpath }}
              
          resources:
            {{ .Values.resources_apache | toYaml | nindent 12 | trim }}    
        - name: {{ .Values.sidecar.name}}
          image: {{ .Values.sidecar.image }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - mountPath: {{ .Values.igate_apache_logs.sidecar_mountPath }}
              name: {{ .Values.igate_apache_logs.name }}
            - mountPath: {{ .Values.sidecar_configmap.mountPath }}
              name: {{ .Values.sidecar_configmap.name }}   
          resources:
            {{ .Values.resources_sidecar | toYaml | nindent 12 | trim }}      
      volumes:
        - name: {{ .Values.igate_mount.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.igate_mount.persistentVolumeClaim }}
        - name: {{ .Values.csv_to_iporting.name}}
          persistentVolumeClaim:
            claimName: {{ .Values.csv_to_iporting.persistentVolumeClaim }}
        - name: {{ .Values.igate_apache_logs.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.igate_apache_logs.persistentVolumeClaim }}
        - name: {{ .Values.sidecar_configmap.name }}
          configMap:
            name: {{ .Values.sidecar_configmap.name }}
        - name: {{ .Values.configmap_getdataphp.name }}
          configMap:
            name: {{ .Values.configmap_getdataphp.name  }}
            defaultMode: 0777
        - name: {{ .Values.configmap_getdatavariablephp.name }}
          configMap:
            name: {{ .Values.configmap_getdatavariablephp.name  }}
            defaultMode: 0777